## numpy-random

### 随机浮点数

In [1]:
import numpy as np
print(np.random.rand())
print(np.random.rand(5))
print(np.random.rand(3,4))

0.43968146499683625
[0.80751124 0.59160875 0.28913398 0.30624827 0.30785923]
[[0.04595238 0.3304233  0.30651561 0.89816967]
 [0.81897357 0.22207488 0.6739661  0.52542451]
 [0.97855799 0.80276693 0.89278212 0.30122348]]


### 随机整数

In [2]:
## [0,20) 之间的随机数
print(np.random.randint(20, size=(3,3)))
## 在 [0,10)之间找 3 个随机数
print(np.random.randint(0,10,3))

[[ 3  6 17]
 [ 6  4 17]
 [12 12  1]]
[4 7 3]


### 设置输出精度

In [3]:
np.set_printoptions(precision = 2)
np.random.rand(2,2)

array([[0.09, 0.64],
       [0.67, 0.95]])

### 洗牌

In [4]:
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

[7 4 3 9 8 0 6 1 5 2]


### 随机种子

In [7]:
## 种子相同，每次随机出来的结果一致
np.random.seed(2)
print(np.random.randint(0, 10))

8
